name: Upgrade Python Requirements

on:
  schedule:
    # will start the job at midnight every monday (UTC)
    - cron: "0 0 * * 1"
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch against which to create requirements PR"
        required: true
        default: 'master'

jobs:
  call-upgrade-python-requirements-workflow:
    uses: edx/.github/.github/workflows/upgrade-python-requirements.yml@master
    with:
      branch: ${{ github.event.inputs.branch || 'master' }}
      team_reviewers: "enterprise-online-campus"
      email_address: "online-campus@edx.org"
    secrets:
      requirements_bot_github_token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
      requirements_bot_github_email: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
      edx_smtp_username: ${{ secrets.EDX_SMTP_USERNAME }}
      edx_smtp_password: ${{ secrets.EDX_SMTP_PASSWORD }}
